# Build stage: compile the Vite/React app (NL Design System) to static assets.
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_URL_FINDOCS
ARG VITE_URL_OPSTELHULP
ARG VITE_URL_KASVISIE
ARG VITE_URL_INNOVATIEPLATFORM
ARG VITE_URL_BELEIDSASSISTENT
ARG VITE_URL_FINCHAT
ARG VITE_URL_FINCHAT_INNOVATIE
ARG VITE_URL_FINCHAT_ACCEPTATIE
ARG VITE_URL_NOTE
ENV VITE_URL_FINDOCS=$VITE_URL_FINDOCS \
    VITE_URL_OPSTELHULP=$VITE_URL_OPSTELHULP \
    VITE_URL_KASVISIE=$VITE_URL_KASVISIE \
    VITE_URL_INNOVATIEPLATFORM=$VITE_URL_INNOVATIEPLATFORM \
    VITE_URL_BELEIDSASSISTENT=$VITE_URL_BELEIDSASSISTENT \
    VITE_URL_FINCHAT=$VITE_URL_FINCHAT \
    VITE_URL_FINCHAT_INNOVATIE=$VITE_URL_FINCHAT_INNOVATIE \
    VITE_URL_FINCHAT_ACCEPTATIE=$VITE_URL_FINCHAT_ACCEPTATIE \
    VITE_URL_NOTE=$VITE_URL_NOTE
RUN npm run build

# Serve stage: nginx serves the built static bundle.
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
